name: qr_earth
description: "Plastic Recycle App"
publish_to: "none"
version: 0.2.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  http: ^1.2.1
  mobile_scanner: ^5.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
